apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: nginx-web-namespace
  labels:
    app: nginx-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  - name: https
    port: 443
    targetPort: 443
    protocol: TCP
  selector:
    app: nginx-web
