apiVersion: v1
kind: Service
metadata:
  name: nginx-web-service
  namespace: nginx-web-namespace
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 80
    protocol: TCP
  selector:
    app: nginx-web